import * as projectImages from "./utils/index";

const projects = [
  {
    id: "p-1",
    title: "GPGPU Flow Field",
    img: projectImages.p1,
    tags: "Shaders · GPGPU",
    url: "https://three-js-glsl-gpgpu-flowfield-git-620ca4-delafuentejs-projects.vercel.app/",
  },
  {
    id: "p-2",
    title: "GPGPU Particles",
    img: projectImages.p2,
    tags: "Shaders · GPGPU",
    url: "https://r3f-gpgpu-particles-tsl-webgpu.vercel.app/",
  },
  {
    id: "p-3",
    title: "Earth Shaders",
    img: projectImages.p3,
    tags: "Shaders",
    url: "https://three-js-glsl-earth-shaders.vercel.app/",
  },
  {
    id: "p-4",
    title: "Portal Scene",
    img: projectImages.p4,
    tags: "Scene · Shaders · 3D",
    url: "https://react-three-fiber-portal-scene.vercel.app/",
  },
  {
    id: "p-5",
    title: "Saint Seiya",
    img: projectImages.p5,
    tags: "Shaders · Slider · 3D",
    url: "https://r3f-saint-seiya-app.vercel.app/",
  },
  {
    id: "p-6",
    title: "Medieval Scene",
    img: projectImages.p6,
    tags: "Scene · 3D",
    url: "https://r3f-medieval-scene.vercel.app/",
  },
  {
    id: "p-7",
    title: "Animated Galaxy",
    img: projectImages.p7,
    tags: "Shaders",
    url: "https://three-js-glsl-animated-galaxy.vercel.app/",
  },
  {
    id: "p-8",
    title: "Haunted House",
    img: projectImages.p8,
    tags: "Scene · 3D",
    url: "https://three-js-haunted-house-plum.vercel.app/",
  },
  {
    id: "p-9",
    title: "Raging Sea Shading",
    img: projectImages.p9,
    tags: "Shaders · 3D",
    url: "https://three-js-glsl-raging-sea-shading.vercel.app/",
  },
  {
    id: "p-10",
    title: "Hologram Shader",
    img: projectImages.p10,
    tags: "Shaders",
    url: "https://three-js-glsl-hologram-shader.vercel.app/",
  },
  {
    id: "p-11",
    title: "Fireworks Shader",
    img: projectImages.p11,
    tags: "Shaders · VFX",
    url: "https://three-js-glsl-fireworks-shaders.vercel.app/",
  },
  {
    id: "p-12",
    title: "Floating Island VFX-Fireworks",
    img: projectImages.p12,
    tags: "Shaders · VFX · 3D",
    url: "https://r3f-trails-86cg.vercel.app/",
  },
  {
    id: "p-13",
    title: "Animated Photo Magazine",
    img: projectImages.p13,
    tags: "Creative",
    url: "https://r3f-animated-photo-magazine.vercel.app/",
  },
  {
    id: "p-14",
    title: "Red Eagle",
    img: projectImages.p14,
    tags: "3D",
    url: "https://r3f-red-eagle.vercel.app/",
  },
  {
    id: "p-15",
    title: "Art Gallery Shaders",
    img: projectImages.p15,
    tags: "Shaders · 3D",
    url: "https://r3f-3d-art-gallery-shaders.vercel.app/",
  },
  {
    id: "p-16",
    title: "Cursor Animation Particles",
    img: projectImages.p16,
    tags: "Shaders",
    url: "https://three-js-glsl-cursor-animation-particles-shader.vercel.app/",
  },
  {
    id: "p-17",
    title: "Particles Morphing Shader",
    img: projectImages.p17,
    tags: "Shaders",
    url: "https://three-js-glsl-particles-morphing-shader.vercel.app/",
  },
  {
    id: "p-18",
    title: "Procedural Terrain Shader",
    img: projectImages.p18,
    tags: "Shaders",
    url: "https://three-js-glsl-procedural-terrain-shader.vercel.app/",
  },
  {
    id: "p-19",
    title: "Coffee Smoke Shader",
    img: projectImages.p19,
    tags: "Shaders · 3D",
    url: "https://three-js-glsl-coffe-smoke-shader.vercel.app/",
  },
  {
    id: "p-20",
    title: "iPhone 15 Pro",
    img: projectImages.p20,
    tags: "Landing · 3D",
    url: "https://r3f-iphone15-pro-clone.vercel.app/",
  },
  {
    id: "p-21",
    title: "MacBook Pro",
    img: projectImages.p21,
    tags: "Landing · 3D",
    url: "https://r3f-landing-page-macbook.vercel.app/",
  },
  {
    id: "p-22",
    title: "Mntn",
    img: projectImages.p22,
    tags: "Landing",
    url: "https://react-gsap-landing-page-mntn.vercel.app/",
  },
  {
    id: "p-23",
    title: "Cocktails",
    img: projectImages.p23,
    tags: "Landing",
    url: "https://react-gsap-cocktails.vercel.app/",
  },
  {
    id: "p-24",
    title: "Overlay Loading",
    img: projectImages.p24,
    tags: "Creative",
    url: "https://three-js-glsl-overlay-loading-html.vercel.app/",
  },
  {
    id: "p-25",
    title: "3D Infinite Slider",
    img: projectImages.p25,
    tags: "Slider · 3D",
    url: "https://three-js-3-d-infinitive-slider.vercel.app/",
  },
  {
    id: "p-26",
    title: "3D Image Globe",
    img: projectImages.p26,
    tags: "Creative",
    url: "https://3d-image-globe.vercel.app/",
  },
  {
    id: "p-27",
    title: "Warp Liquid Frames Slider",
    img: projectImages.p27,
    tags: "Shaders · Slider",
    url: "https://three-js-shaders-warp-liquid-frames.vercel.app/",
  },
  {
    id: "p-28",
    title: "3D Fake Image Gallery",
    img: projectImages.p28,
    tags: "Shaders · 3D",
    url: "https://react-threejs-glsl-fake-3d-images-g.vercel.app/",
  },
  {
    id: "p-29",
    title: "3D Fake Sunrays",
    img: projectImages.p29,
    tags: "Shaders",
    url: "https://react-glsl-images-gallery-magnifyin.vercel.app/",
  },
  {
    id: "p-30",
    title: "Magnifying Glass Image Gallery",
    img: projectImages.p30,
    tags: "Shaders",
    url: "https://react-glsl-images-gallery-magnifyin.vercel.app/",
  },
  {
    id: "p-31",
    title: "Awwwards Clone: Spylt",
    img: projectImages.p31,
    tags: "Landing",
    url: "https://react-awwards-spylt-clone.vercel.app/",
  },
  {
    id: "p-32",
    title: "Awwwards Clone: Zentry",
    img: projectImages.p32,
    tags: "Landing",
    url: "https://react-awwards.vercel.app/",
  },
  {
    id: "p-33",
    title: "Awwwards Clone: Adidas / Foot Locker",
    img: projectImages.p33,
    tags: "Landing",
    url: "#",
  },
  {
    id: "p-34",
    title: "Parallax Effect GSAP",
    img: projectImages.p34,
    tags: "GSAP",
    url: "https://react-3d-parallax.vercel.app/",
  },
  {
    id: "p-35",
    title: "Sliced Model Shader",
    img: projectImages.p35,
    tags: "Shaders",
    url: "https://three-js-glsl-sliced-model-shader.vercel.app/",
  },
  {
    id: "p-36",
    title: "Wobbly Sphere",
    img: projectImages.p36,
    tags: "Shaders",
    url: "https://three-js-csm-wobbly-sphere.vercel.app/",
  },
  {
    id: "p-37",
    title: "Post-Processing",
    img: projectImages.p37,
    tags: "Shaders · FX",
    url: "https://three-js-glsl-post-processing.vercel.app/",
  },
  {
    id: "p-38",
    title: "Obstacle Race",
    img: projectImages.p38,
    tags: "Game · 3D",
    url: "https://r3f-obstacles-race-game.vercel.app/",
  },
  {
    id: "p-39",
    title: "Wizard",
    img: projectImages.p39,
    tags: "3D",
    url: "#",
  },
  {
    id: "p-40",
    title: "Rock Paper Scissors",
    img: projectImages.p40,
    tags: "Game",
    url: "#",
  },
  {
    id: "p-41",
    title: "Web Creative Agency",
    img: projectImages.p41,
    tags: "Landing · 3D",
    url: "https://r3f-3d-web-creative-agency-demo.vercel.app/",
  },
  {
    id: "p-42",
    title: "3D Tesla Model",
    img: projectImages.p42,
    tags: "3D",
    url: "https://r3f-staging.vercel.app/",
  },
  {
    id: "p-43",
    title: "F1 Ferrari Racing",
    img: projectImages.p43,
    tags: "3D",
    url: "https://r3f-webgpu-tsl-intro.vercel.app/",
  },
  {
    id: "p-44",
    title: "Models Environment",
    img: projectImages.p44,
    tags: "3D Scene",
    url: "https://r3f-staging.vercel.app/",
  },
];

export default projects;
